"use node";

import { openai } from "@ai-sdk/openai";
import { getChatModelProviderOptions } from "@workspace/ai/models";
import { finalizeOpenAIToolSet } from "@workspace/ai/openai-tool-search";
import { BASE_CHAT_SYSTEM_PROMPT } from "@workspace/ai/prompts";
import { ToolLoopAgent } from "ai";
import { v } from "convex/values";
import { internal } from "./_generated/api";
import { internalAction } from "./_generated/server";
import { buildServerWorkspaceTools } from "./serverWorkspaceTools";

const MAX_AUTOMATION_HISTORY_MESSAGES = 40;

const automationRunReasonValidator = v.union(
	v.literal("scheduled"),
	v.literal("manual"),
);

const createMessageId = () =>
	`msg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

const createTextMessage = ({
	id,
	role,
	text,
	metadata,
}: {
	id: string;
	role: "user" | "assistant";
	text: string;
	metadata: Record<string, unknown>;
}) => ({
	id,
	role,
	partsJson: JSON.stringify([{ type: "text", text }]),
	metadataJson: JSON.stringify(metadata),
	text,
	createdAt: Date.now(),
});

const buildAutomationSystemPrompt = ({
	targetLabel,
	webSearchEnabled,
	appSources,
	notes,
}: {
	targetLabel: string;
	webSearchEnabled: boolean;
	appSources: Array<{ label: string }>;
	notes: Array<{ title: string; text: string; updatedAt: number }>;
}) => {
	const noteContext = notes
		.map((note) =>
			[
				`Title: ${note.title}`,
				`Updated: ${new Date(note.updatedAt).toISOString()}`,
				note.text,
			].join("\n"),
		)
		.join("\n\n---\n\n");

	return [
		BASE_CHAT_SYSTEM_PROMPT,
		"This response is being generated by a scheduled automation.",
		`Automation target: ${targetLabel}.`,
		webSearchEnabled
			? "Web search is enabled. Use web search when current or external information is needed."
			: "",
		appSources.length > 0
			? `Selected sources: ${appSources.map((source) => source.label).join(", ")}.`
			: "",
		"Use the automation prompt as the task. If project notes are provided, use them as context and do not invent missing facts.",
		noteContext ? `Recent project notes:\n\n${noteContext}` : "",
	]
		.filter(Boolean)
		.join("\n\n");
};

export const runAutomation = internalAction({
	args: {
		automationId: v.id("automations"),
		scheduledFor: v.number(),
		reason: automationRunReasonValidator,
		reservedRunId: v.optional(v.id("automationRuns")),
	},
	returns: v.null(),
	handler: async (ctx, args) => {
		if (!process.env.OPENAI_API_KEY) {
			throw new Error("OPENAI_API_KEY is not configured in Convex.");
		}

		const run = args.reservedRunId
			? await ctx.runMutation(internal.automations.activateRun, {
					automationId: args.automationId,
					runId: args.reservedRunId,
					scheduledFor: args.scheduledFor,
					reason: args.reason,
				})
			: await ctx.runMutation(internal.automations.beginRun, args);
		if (run.status !== "started") {
			return null;
		}

		const userMessageId = createMessageId();
		const assistantMessageId = createMessageId();
		const metadata = {
			source: "automation",
			automationId: String(run.automationId),
			automationRunId: String(run.runId),
			scheduledFor: run.scheduledFor,
			reason: run.reason,
		};

		try {
			const isActiveBeforeUserMessage = await ctx.runMutation(
				internal.automations.isRunActive,
				{
					automationId: run.automationId,
					runId: run.runId,
				},
			);
			if (!isActiveBeforeUserMessage) {
				return null;
			}

			await ctx.runMutation(internal.chats.saveMessageForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				authorName: run.authorName,
				chatId: run.chatId,
				title: run.title,
				preview: run.prompt,
				model: run.model,
				reasoningEffort: run.reasoningEffort,
				forceTitle: true,
				message: createTextMessage({
					id: userMessageId,
					role: "user",
					text: run.prompt,
					metadata,
				}),
			});

			const history = await ctx.runQuery(internal.chats.getMessagesForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				chatId: run.chatId,
			});
			const messages = history
				.slice(-MAX_AUTOMATION_HISTORY_MESSAGES)
				.filter(
					(message) =>
						(message.role === "user" || message.role === "assistant") &&
						message.text.trim(),
				)
				.map((message) => ({
					role: message.role,
					content: message.text,
				}));
			const { tools: appTools } = run.appsEnabled
				? await buildServerWorkspaceTools(ctx, {
						ownerTokenIdentifier: run.ownerTokenIdentifier,
						workspaceId: run.workspaceId,
						selectedSourceIds: run.appSources.map((source) => source.id),
					})
				: { tools: {} };
			const finalizedToolSet = finalizeOpenAIToolSet({
				...(run.webSearchEnabled
					? {
							web_search: openai.tools.webSearch({
								searchContextSize: "medium",
								userLocation: {
									type: "approximate" as const,
									country: "US" as const,
								},
							}),
						}
					: {}),
				...appTools,
			});
			const { tools } = finalizedToolSet;
			const automationAgent = new ToolLoopAgent({
				id: "automation-runner",
				model: openai(run.model),
				providerOptions: getChatModelProviderOptions(run.model, {
					reasoningEffort: run.reasoningEffort,
				}),
				instructions: buildAutomationSystemPrompt({
					targetLabel: run.targetLabel,
					webSearchEnabled: run.webSearchEnabled,
					appSources: run.appSources,
					notes: run.notes,
				}),
				tools: finalizedToolSet.hasTools ? tools : undefined,
			});
			const result = await automationAgent.generate({
				messages,
			});

			const isActiveBeforeAssistantMessage = await ctx.runMutation(
				internal.automations.isRunActive,
				{
					automationId: run.automationId,
					runId: run.runId,
				},
			);
			if (!isActiveBeforeAssistantMessage) {
				return null;
			}

			await ctx.runMutation(internal.chats.saveMessageForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				authorName: run.authorName,
				chatId: run.chatId,
				title: run.title,
				preview: result.text,
				model: run.model,
				reasoningEffort: run.reasoningEffort,
				forceTitle: true,
				message: createTextMessage({
					id: assistantMessageId,
					role: "assistant",
					text: result.text,
					metadata,
				}),
			});

			await ctx.runMutation(internal.automations.completeRun, {
				automationId: run.automationId,
				runId: run.runId,
				userMessageId,
				assistantMessageId,
			});
		} catch (error) {
			const errorMessage =
				error instanceof Error ? error.message : String(error);
			const isActiveBeforeFailureMessage = await ctx.runMutation(
				internal.automations.isRunActive,
				{
					automationId: run.automationId,
					runId: run.runId,
				},
			);
			if (!isActiveBeforeFailureMessage) {
				return null;
			}
			try {
				await ctx.runMutation(internal.chats.saveMessageForOwner, {
					ownerTokenIdentifier: run.ownerTokenIdentifier,
					workspaceId: run.workspaceId,
					authorName: run.authorName,
					chatId: run.chatId,
					title: run.title,
					preview: "Automation run failed.",
					model: run.model,
					reasoningEffort: run.reasoningEffort,
					forceTitle: true,
					message: createTextMessage({
						id: assistantMessageId,
						role: "assistant",
						text: [
							"Automation run failed.",
							"",
							"I could not complete this scheduled run. The automation remains scheduled for future runs unless it is paused or deleted.",
						].join("\n"),
						metadata: {
							...metadata,
							event: "failed",
							error: errorMessage,
						},
					}),
				});
			} catch (messageError) {
				console.error(
					"Failed to save automation failure message",
					messageError,
				);
			}
			await ctx.runMutation(internal.automations.failRun, {
				automationId: run.automationId,
				runId: run.runId,
				error: errorMessage,
			});
			throw error;
		}

		return null;
	},
});
