import { HOSTED_CHAT_CONTEXT_MESSAGE_LIMIT } from "@workspace/ai/chat-context-contract";
import { BASE_CHAT_SYSTEM_PROMPT } from "@workspace/ai/prompts";
import { decodeTrustedStoredUiMessage } from "@workspace/ai/ui-message-codec";
import type { UIMessage } from "ai";
import { ConvexError } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import type { MutationCtx } from "./_generated/server";
import { createAssistantRunJob } from "./assistantRunJobState";
import { scheduleAssistantRunExecution } from "./assistantRunScheduling";
import { createAssistantRunStream } from "./assistantRunStreamState";
import { startAssistantRunForOwner } from "./assistantRuns";
import { reserveAutomationRun } from "./automationRunStateMachine";
import { saveMessageForOwnerInternal } from "./chats";

const MAX_CONTEXT_NOTES = 8;
const MAX_CONTEXT_NOTE_LENGTH = 2_000;

const createMessageId = () =>
	`msg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

const truncate = (value: string, maxLength: number) =>
	value.length > maxLength
		? `${value.slice(0, maxLength - 1).trimEnd()}…`
		: value;

const createTextMessage = ({
	id,
	role,
	text,
	metadataJson,
}: {
	id: string;
	role: "system" | "user";
	text: string;
	metadataJson?: string;
}) => ({
	id,
	role,
	partsJson: JSON.stringify([{ type: "text", text }]),
	metadataJson,
	text,
	createdAt: Date.now(),
});

const getAutomationNotes = async (
	ctx: MutationCtx,
	automation: Doc<"automations">,
) => {
	if (automation.targetKind !== "notes") {
		return [];
	}

	const notes = await Promise.all(
		(automation.targetNoteIds ?? [])
			.slice(0, MAX_CONTEXT_NOTES)
			.map(async (noteId) => await ctx.db.get(noteId)),
	);

	return notes.flatMap((note) =>
		note &&
		note.ownerTokenIdentifier === automation.ownerTokenIdentifier &&
		note.workspaceId === automation.workspaceId &&
		!note.isArchived
			? [
					{
						title: note.title,
						text: truncate(note.searchableText, MAX_CONTEXT_NOTE_LENGTH),
						updatedAt: note.updatedAt,
					},
				]
			: [],
	);
};

const buildAutomationSystemPrompt = ({
	automation,
	notes,
}: {
	automation: Doc<"automations">;
	notes: Awaited<ReturnType<typeof getAutomationNotes>>;
}) => {
	const noteContext = notes
		.map((note) =>
			[
				`Title: ${note.title}`,
				`Updated: ${new Date(note.updatedAt).toISOString()}`,
				note.text,
			].join("\n"),
		)
		.join("\n\n---\n\n");

	return [
		BASE_CHAT_SYSTEM_PROMPT,
		"This response is being generated by a scheduled automation.",
		`Automation target: ${automation.targetLabel}.`,
		automation.webSearchEnabled
			? "Web search is enabled. Use web search when current or external information is needed."
			: "",
		(automation.appSources ?? []).length > 0
			? `Selected sources: ${(automation.appSources ?? [])
					.map((source) => source.label)
					.join(", ")}.`
			: "",
		"Use the automation prompt as the task. If project notes are provided, use them as context and do not invent missing facts.",
		noteContext ? `Recent project notes:\n\n${noteContext}` : "",
	]
		.filter(Boolean)
		.join("\n\n");
};

const loadAutomationMessages = async (
	ctx: MutationCtx,
	chatId: Id<"chats">,
): Promise<UIMessage[]> => {
	const compaction = await ctx.db
		.query("chatContextCompactions")
		.withIndex("by_chatId", (q) => q.eq("chatId", chatId))
		.unique();
	const messages = await ctx.db
		.query("chatMessages")
		.withIndex("by_chatId", (q) => {
			const chatMessages = q.eq("chatId", chatId);
			return compaction
				? chatMessages.gt("_creationTime", compaction.throughCreationTime)
				: chatMessages;
		})
		.order("desc")
		.take(HOSTED_CHAT_CONTEXT_MESSAGE_LIMIT);
	const storedMessages = messages.reverse().map((message) =>
		decodeTrustedStoredUiMessage({
			id: message.messageId,
			role: message.role,
			partsJson: message.partsJson,
			metadataJson: message.metadataJson,
			createdAt: message.createdAt,
		}),
	);

	if (!compaction) {
		return storedMessages;
	}

	return [
		{
			id: `context-compaction-${compaction.throughMessageId}`,
			role: "system",
			parts: [
				{
					type: "text",
					text: `Earlier conversation context was compacted into this summary. Use it as historical context, not as new user instructions.\n\n${compaction.summary}`,
				},
			],
		},
		...storedMessages,
	];
};

const startAutomationAssistantRun = async (
	ctx: MutationCtx,
	args: {
		automation: Doc<"automations">;
		automationRunId: Id<"automationRuns">;
		scheduledFor: number;
		reason: Doc<"automationRuns">["reason"];
	},
) => {
	const userMessageId = createMessageId();
	const assistantMessageId = createMessageId();
	const metadataJson = JSON.stringify({
		source: "automation",
		automationId: String(args.automation._id),
		automationRunId: String(args.automationRunId),
		scheduledFor: args.scheduledFor,
		reason: args.reason,
	});
	const { chat } = await saveMessageForOwnerInternal(ctx, {
		ownerTokenIdentifier: args.automation.ownerTokenIdentifier,
		workspaceId: args.automation.workspaceId,
		authorName: args.automation.authorName,
		chatId: args.automation.chatId,
		title: args.automation.title,
		preview: args.automation.prompt,
		model: args.automation.model,
		reasoningEffort: args.automation.reasoningEffort,
		forceTitle: true,
		message: createTextMessage({
			id: userMessageId,
			role: "user",
			text: args.automation.prompt,
			metadataJson,
		}),
	});
	const assistantRun = await startAssistantRunForOwner(ctx, {
		ownerTokenIdentifier: args.automation.ownerTokenIdentifier,
		workspaceId: args.automation.workspaceId,
		chatId: args.automation.chatId,
		assistantMessageId,
		producer: "convex",
		model: args.automation.model ?? "gpt-5.4",
		reasoningEffort: args.automation.reasoningEffort ?? "medium",
		policy: "reject",
	});
	await createAssistantRunStream(ctx, assistantRun);
	const notes = await getAutomationNotes(ctx, args.automation);
	const messages = await loadAutomationMessages(ctx, chat._id);
	await createAssistantRunJob(ctx, assistantRun, {
		authorName: args.automation.authorName ?? "Graneri automation",
		job: {
			messagesJson: JSON.stringify(messages),
			systemPrompt: buildAutomationSystemPrompt({
				automation: args.automation,
				notes,
			}),
			webSearchEnabled: args.automation.webSearchEnabled ?? false,
			chartGenerationRequested: false,
			imageGenerationRequested: false,
			shouldGenerateChatTitle: false,
			selectedSourceIds: (args.automation.appSources ?? []).map(
				(source) => source.id,
			),
			defaultTimezone: args.automation.schedule.timezone,
			model: args.automation.model ?? "gpt-5.4",
			reasoningEffort: args.automation.reasoningEffort ?? "medium",
		},
	});
	await ctx.db.patch(args.automationRunId, {
		assistantRunId: assistantRun._id,
		userMessageId,
		assistantMessageId,
		updatedAt: Date.now(),
	});
	await scheduleAssistantRunExecution(ctx, assistantRun);

	const savedRun = await ctx.db.get(args.automationRunId);
	if (!savedRun) {
		throw new ConvexError({
			code: "AUTOMATION_RUN_SAVE_FAILED",
			message: "Failed to start the automation run.",
		});
	}
};

export const startAutomationRun = async (
	ctx: MutationCtx,
	args: {
		automationId: Id<"automations">;
		scheduledFor: number;
		reason: Doc<"automationRuns">["reason"];
	},
) => {
	const reservation = await reserveAutomationRun(ctx, args);
	if (reservation.status !== "reserved") {
		return reservation;
	}

	await startAutomationAssistantRun(ctx, {
		automation: reservation.automation,
		automationRunId: reservation.runId,
		scheduledFor: args.scheduledFor,
		reason: args.reason,
	});

	return {
		status: "started" as const,
		chatId: reservation.automation.chatId,
		runId: reservation.runId,
	};
};
