import { CHAT_CONTEXT_POLICY } from "@workspace/ai/chat-context-policy";
import {
	DEFAULT_CHAT_SETTINGS,
	selectChatSettings,
} from "@workspace/ai/chat-settings";
import { findChatModel } from "@workspace/ai/models";
import {
	BASE_CHAT_INSTRUCTIONS,
	buildChatHistoryInstructions,
} from "@workspace/ai/prompts";
import { projectStoredUiMessagesForAssistantRun } from "@workspace/ai/stored-ui-message-context";
import type { UIMessage } from "ai";
import { ConvexError } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import type { MutationCtx } from "./_generated/server";
import { createAssistantRunJob } from "./assistantRunJobState";
import { scheduleAssistantRunExecution } from "./assistantRunScheduling";
import { createAssistantRunStream } from "./assistantRunStreamState";
import { startAssistantRunForOwner } from "./assistantRuns";
import { reserveAutomationRun } from "./automationRunStateMachine";
import { getChatContextCheckpoint } from "./chatContextCompactions";
import type { ChatSettings } from "./chatSettingsModel";
import { saveMessageForOwnerInternal } from "./chats";

const MAX_CONTEXT_NOTES = 8;
const MAX_CONTEXT_NOTE_LENGTH = 2_000;

const createMessageId = () =>
	`msg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

const truncate = (value: string, maxLength: number) =>
	value.length > maxLength
		? `${value.slice(0, maxLength - 1).trimEnd()}…`
		: value;

const createTextMessage = ({
	id,
	role,
	text,
	metadataJson,
}: {
	id: string;
	role: "user";
	text: string;
	metadataJson?: string;
}) => ({
	id,
	role,
	partsJson: JSON.stringify([{ type: "text", text }]),
	metadataJson,
	text,
	createdAt: Date.now(),
});

const getAutomationNotes = async (
	ctx: MutationCtx,
	automation: Doc<"automations">,
) => {
	if (automation.targetKind !== "notes") {
		return [];
	}

	const notes = await Promise.all(
		(automation.targetNoteIds ?? [])
			.slice(0, MAX_CONTEXT_NOTES)
			.map(async (noteId) => await ctx.db.get(noteId)),
	);

	return notes.flatMap((note) =>
		note &&
		note.ownerTokenIdentifier === automation.ownerTokenIdentifier &&
		note.workspaceId === automation.workspaceId &&
		!note.isArchived
			? [
					{
						title: note.title,
						text: truncate(note.searchableText, MAX_CONTEXT_NOTE_LENGTH),
						updatedAt: note.updatedAt,
					},
				]
			: [],
	);
};

const buildAutomationInstructions = ({
	automation,
	compactionSummary,
	notes,
	webSearchEnabled,
}: {
	automation: Doc<"automations">;
	compactionSummary: string | null;
	notes: Awaited<ReturnType<typeof getAutomationNotes>>;
	webSearchEnabled: boolean;
}) => {
	const noteContext = notes
		.map((note) =>
			[
				`Title: ${note.title}`,
				`Updated: ${new Date(note.updatedAt).toISOString()}`,
				note.text,
			].join("\n"),
		)
		.join("\n\n---\n\n");

	return [
		BASE_CHAT_INSTRUCTIONS,
		"This response is being generated by a scheduled automation.",
		`Automation target: ${automation.targetLabel}.`,
		webSearchEnabled
			? "Web search is enabled. Use web search when current or external information is needed."
			: "",
		(automation.appSources ?? []).length > 0
			? `Selected sources: ${(automation.appSources ?? [])
					.map((source) => source.label)
					.join(", ")}.`
			: "",
		"Use the automation prompt as the task. If project notes are provided, use them as context and do not invent missing facts.",
		compactionSummary === null
			? ""
			: buildChatHistoryInstructions(compactionSummary),
		noteContext ? `Recent project notes:\n\n${noteContext}` : "",
	]
		.filter(Boolean)
		.join("\n\n");
};

const loadAutomationMessages = async (
	ctx: MutationCtx,
	chatId: Id<"chats">,
): Promise<{ compactionSummary: string | null; messages: UIMessage[] }> => {
	const compaction = await getChatContextCheckpoint(ctx, chatId);
	const messages = await ctx.db
		.query("chatMessages")
		.withIndex("by_chatId", (q) => {
			const chatMessages = q.eq("chatId", chatId);
			return compaction
				? chatMessages.gt("_creationTime", compaction.throughCreationTime)
				: chatMessages;
		})
		.order("desc")
		.take(CHAT_CONTEXT_POLICY.exactTailMessageLimit);
	const storedMessages = projectStoredUiMessagesForAssistantRun(
		messages.reverse().map((message) => ({
			id: message.messageId,
			role: message.role,
			partsJson: message.partsJson,
			metadataJson: message.metadataJson,
		})),
	);

	return {
		compactionSummary: compaction?.summary ?? null,
		messages: storedMessages,
	};
};

const getAutomationRunSettings = ({
	automation,
	chat,
}: {
	automation: Doc<"automations">;
	chat: Doc<"chats"> | null;
}): ChatSettings => {
	if (automation.destination === "current_chat") {
		if (!chat) {
			throw new ConvexError({
				code: "CHAT_NOT_FOUND",
				message: "Automation chat not found.",
			});
		}

		return selectChatSettings(chat);
	}

	const model = findChatModel(automation.model)?.model;
	if (!model) {
		throw new ConvexError({
			code: "AUTOMATION_MODEL_CONFIGURATION_MISSING",
			message: "Automation model configuration is missing.",
		});
	}

	return {
		...DEFAULT_CHAT_SETTINGS,
		model,
		reasoningEffort: automation.reasoningEffort,
		serviceTier: automation.serviceTier,
		webSearchEnabled: automation.webSearchEnabled,
	};
};

const startAutomationAssistantRun = async (
	ctx: MutationCtx,
	args: {
		automation: Doc<"automations">;
		automationRunId: Id<"automationRuns">;
		chat: Doc<"chats"> | null;
		scheduledFor: number;
		reason: Doc<"automationRuns">["reason"];
	},
) => {
	const settings = getAutomationRunSettings({
		automation: args.automation,
		chat: args.chat,
	});
	const ownsDestinationChat = args.automation.destination === "standalone";
	const userMessageId = createMessageId();
	const assistantMessageId = createMessageId();
	const metadataJson = JSON.stringify({
		source: "automation",
		automationId: String(args.automation._id),
		automationRunId: String(args.automationRunId),
		scheduledFor: args.scheduledFor,
		reason: args.reason,
	});
	const { chat } = await saveMessageForOwnerInternal(ctx, {
		ownerTokenIdentifier: args.automation.ownerTokenIdentifier,
		workspaceId: args.automation.workspaceId,
		authorName: args.automation.authorName,
		chatId: args.automation.chatId,
		projectId: ownsDestinationChat ? args.automation.projectId : undefined,
		title: ownsDestinationChat ? args.automation.title : undefined,
		preview: args.automation.prompt,
		settings: ownsDestinationChat ? settings : undefined,
		forceTitle: ownsDestinationChat,
		message: createTextMessage({
			id: userMessageId,
			role: "user",
			text: args.automation.prompt,
			metadataJson,
		}),
	});
	const assistantRun = await startAssistantRunForOwner(ctx, {
		ownerTokenIdentifier: args.automation.ownerTokenIdentifier,
		workspaceId: args.automation.workspaceId,
		chatId: args.automation.chatId,
		assistantMessageId,
		producer: "convex",
		localCapabilitySession: null,
		model: settings.model,
		reasoningEffort: settings.reasoningEffort,
		serviceTier: settings.serviceTier,
		policy: "reject",
	});
	await createAssistantRunStream(ctx, assistantRun);
	const notes = await getAutomationNotes(ctx, args.automation);
	const { compactionSummary, messages } = await loadAutomationMessages(
		ctx,
		chat._id,
	);
	await createAssistantRunJob(ctx, assistantRun, {
		authorName: args.automation.authorName ?? "Graneri automation",
		googleAuthUserId: null,
		job: {
			messagesJson: JSON.stringify(messages),
			instructions: buildAutomationInstructions({
				automation: args.automation,
				compactionSummary,
				notes,
				webSearchEnabled: settings.webSearchEnabled,
			}),
			chatMode: settings.chatMode,
			webSearchEnabled: settings.webSearchEnabled,
			chartGenerationRequested: false,
			imageGenerationRequested: false,
			appToolScope: args.automation.appsEnabled ? "selected" : "disabled",
			shouldGenerateChatTitle: false,
			selectedSourceIds: (args.automation.appSources ?? []).map(
				(source) => source.id,
			),
			defaultTimezone: args.automation.schedule.timezone,
			model: settings.model,
			reasoningEffort: settings.reasoningEffort,
			serviceTier: settings.serviceTier,
		},
	});
	await ctx.db.patch(args.automationRunId, {
		assistantRunId: assistantRun._id,
		userMessageId,
		assistantMessageId,
		updatedAt: Date.now(),
	});
	await scheduleAssistantRunExecution(ctx, assistantRun);

	const savedRun = await ctx.db.get(args.automationRunId);
	if (!savedRun) {
		throw new ConvexError({
			code: "AUTOMATION_RUN_SAVE_FAILED",
			message: "Failed to start the automation run.",
		});
	}
};

export const startAutomationRun = async (
	ctx: MutationCtx,
	args: {
		automationId: Id<"automations">;
		scheduledFor: number;
		reason: Doc<"automationRuns">["reason"];
	},
) => {
	const reservation = await reserveAutomationRun(ctx, args);
	if (reservation.status !== "reserved") {
		return reservation;
	}

	await startAutomationAssistantRun(ctx, {
		automation: reservation.automation,
		automationRunId: reservation.runId,
		chat: reservation.chat,
		scheduledFor: args.scheduledFor,
		reason: args.reason,
	});

	return {
		status: "started" as const,
		chatId: reservation.automation.chatId,
		runId: reservation.runId,
	};
};
